version: "3.9"

services:
  # Redis (for state tracking + caching)
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/opt/redis
    networks:
      - pipeline-net

  # Spark Master
  spark-master:
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark-master
    environment:
      - SPARK_NO_DAEMONIZE=true
    build:
      context: ./spark
      dockerfile: Dockerfile.spark
    volumes:
      - ./processing:/opt/mnt/processing
      - ./data:/opt/mnt/data
    ports:
      - "7077:7077"
      - "8080:8080"    # Spark Master UI
    networks:
      - pipeline-net

  # Spark Worker
  spark-worker:
    container_name: spark-worker
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
    build:
      context: ./spark
      dockerfile: Dockerfile.spark
    depends_on:
      - spark-master
    volumes:
      - ./processing:/opt/mnt/processing
      - ./data:/opt/mnt/data
    ports:
      - "8081:8081"    # Spark Worker UI
    networks:
      - pipeline-net

  # Airflow (SequentialExecutor)
  # Works with SQLite so no Postgres required
  airflow:
    container_name: airflow
    build:
      context: ./airflow
      dockerfile: Dockerfile.airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor   # IMPORTANT: works with SQLite
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./processing:/opt/mnt/processing
      - ./data:/opt/mnt/data
    ports:
      - "8085:8080"   # Airflow UI
    entrypoint: ["/bin/bash", "/opt/airflow/startup.sh"]
    depends_on:
      - redis
      - spark-master
      - spark-worker
    networks:
      - pipeline-net

networks:
  pipeline-net:
    driver: bridge
